services:

  prototype:
    image: node:22
    working_dir: /app
    volumes:
      - ../vibe-financas-magicas:/app
      - prototype_node_modules:/app/node_modules
    tty: true
    stdin_open: true
    command: >
      sh -c "
        if [ ! -d node_modules ]; then
          echo '📦 Installing dependencies...' &&
          npm install;
        fi &&
        echo '🚀 Starting dev server...' &&
        exec npm run dev
      " 
  web:
    image: node:22
    working_dir: /app
    volumes:
      - ./Web:/app
      - .git:/app/.git
      - web_node_modules:/app/node_modules
    command:
      - sh
      - -c
      - yarn install && yarn start

  proxy:
    restart: always
    image: node:22
    working_dir: /app
    volumes:
      - proxy_node_modules:/app/node_modules
      - ./firebase.json:/app/firebase.json
      - ./Web/proxy:/app
    ports:
      - "443:4433"
      - "80:8080"
    command:
      - sh
      - -c
      - yarn install && yarn proxy

  backend-builder:
    image: node:22
    working_dir: /app
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
    command: yarn docker

  firebase:
    build:
      context: ./Firebase
    volumes:
      - ./.firebaserc:/app/.firebaserc
      - ./firebase.json:/app/firebase.json
      - ./Firebase:/app/Firebase
      - ./Backend:/app/Backend
      - ./Backend/.env.local:/app/.env.local
    ports:
      - "8004:8004" # Auth
      - "8006:8006" # Functions
      - "8008:8008" # Firestore
      - "8010:8010" # Hosting
      - "4000:4000" # Emulator UI
      - "4400:4400" # Hub
      - "4500:4500" # Other reserved ports
      - "9150:9150" # Other reserved ports
      - "9299:9299" # ???
    command: firebase emulators:start --import=./Firebase/data --export-on-exit=./Firebase/data

volumes:
  proxy_node_modules:
  web_node_modules:
  prototype_node_modules:
  backend_node_modules:
