services:
  web:
    restart: always
    build:
      context: ./Web/configs
    volumes:
      - ./Web:/app
      - web_node_modules:/app/node_modules
    command:
      - sh
      - -c
      - yarn install && yarn start
    depends_on:
      - firebase

  proxy:
    restart: always
    build:
      context: ./Web/configs
    volumes:
      - ./Web:/app
      - ./firebase.json:/app/firebase.json
      - proxy_node_modules:/app/node_modules
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    command:
      - sh
      - -c
      - yarn install && yarn proxy

  backend-builder:
    restart: always
    image: node:22
    working_dir: /app
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
    command: yarn docker

  firebase:
    restart: always
    build:
      context: ./Firebase
    volumes:
      - ./Firebase:/app/emulators
      - ./.firebaserc:/app/.firebaserc
      - ./Backend:/app/Backend
      - ./Backend/.env.local:/app/.env.local
      - ./firebase.json:/app/firebase.json
    ports:
      - "8084:8084" # Auth
      - "8006:8006" # Functions
      - "8008:8008" # Firestore
      - "4000:4000" # Emulator UI
    command: firebase emulators:start --import=./emulators/data --export-on-exit=./emulators/data --only firestore,functions,ui,auth

volumes:
  proxy_node_modules:
  web_node_modules:
  backend_node_modules:
