name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
